Nuxia\ValuelistBundle\Entity\Valuelist:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ["category", "code"]
            message: "valuelist.not_unique"
            groups: ["new", "edit"]
    properties:
        code:
            - NotBlank:
                message: "valuelist.code.blank"
                groups: ["new"]
            - Length:
                max: "32"
                maxMessage: "valuelist.code.long"
                groups: ["new", "edit"]
        label:
            - NotBlank:
                message: "valuelist.label.blank"
                groups: ["new", "edit"]
            - Length:
                max: "64"
                maxMessage: "valuelist.code.long"
                groups: ["new", "edit"]
