parameters:
    nuxia_valuelist.form.type: "nuxia_valuelist_valuelist"

services:
    nuxia_valuelist.admin.controller:
        parent: "nuxia.controller.abstract"
        class: "Nuxia\ValuelistBundle\Controller\AdminController"
        public: false
        calls:
            - [ "setRouter", [ "@router" ] ]
            - [ "setFlashBag", [ "@?session.flash_bag" ] ]
            - [ "setTemplating", [ "@templating" ] ]
            - [ "setValuelistManager", [ "@nuxia_valuelist.manager" ] ]
            - [ "setValuelistFormHandler", [ "@nuxia_valuelist.form.handler" ] ]

    nuxia_valuelist.form.type:
        class: "Nuxia\ValuelistBundle\Form\Type\ValuelistType"
        tags:
            - { name: "form.type", alias: "nuxia_valuelist_valuelist"}

    nuxia_valuelist.form.factory:
        class: "Nuxia\Component\Form\Factory\FormFactory"
        public: false
        arguments:
            - "@form.factory"
            - "%nuxia_valuelist.form.type%"

    nuxia_valuelist.form.handler:
        parent: "nuxia.form.handler.abstract"
        class:  "Nuxia\ValuelistBundle\Form\Handler\ValuelistFormHandler"
        public: false
        calls:
            - [ "setFormFactory", [ "@nuxia_valuelist.form.factory" ] ]
            - [ "setValuelistManager", ["@nuxia_valuelist.manager" ] ]

    nuxia_valuelist.twig.extension:
        class: "Nuxia\ValuelistBundle\Twig\AdminValuelistExtension"
        public: false
        arguments:
            - "@nuxia_valuelist.manager"
        tags:
            - { name: "twig.extension" }
