services:
    nuxia_valuelist_choice.form.type.abstract:
        class: "Nuxia\ValuelistBundle\Form\Type\AbstractValuelistChoiceType"
        abstract: true
        calls:
            - [ "setValuelistManager", [ "@nuxia_valuelist.manager" ] ]

    nuxia_valuelist_choice.form.type:
        parent: "nuxia_valuelist_choice.form.type.abstract"
        class: "Nuxia\ValuelistBundle\Form\Type\ValuelistChoiceType"
        tags:
            - { name: "form.type", alias: "nuxia_valuelist_valuelist_choice" }

    nuxia_valuelist_tree_choice.form.type:
        parent: "nuxia_valuelist_choice.form.type.abstract"
        class: "Nuxia\ValuelistBundle\Form\Type\ValuelistTreeChoiceType"
        tags:
            - { name: "form.type", alias: "nuxia_valuelist_tree_valuelist_choice" }
